# Generated by Django 5.1.2 on 2024-10-20 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCycleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cramp_level', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='Rate your cramp level from 1 (no cramps) to 10 (severe cramps).')),
                ('cycle_start_date', models.DateField(help_text='Enter the start date of your menstrual cycle.')),
                ('cycle_end_date', models.DateField(help_text='Enter the end date of your menstrual cycle.')),
                ('height', models.PositiveIntegerField(help_text='Enter your height in feet.')),
                ('weight', models.PositiveIntegerField(help_text='Enter your weight in pounds.')),
                ('age', models.PositiveIntegerField(help_text='Enter your age in years.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Cycle Data',
                'verbose_name_plural': 'User Cycle Data',
            },
        ),
    ]
