# Generated by Django 5.1.2 on 2024-10-20 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_usercycledata_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercycledata',
            name='cycle_end_date',
        ),
        migrations.RemoveField(
            model_name='usercycledata',
            name='cycle_start_date',
        ),
        migrations.AddField(
            model_name='usercycledata',
            name='current_date',
            field=models.DateField(default=datetime.date.today, help_text='The selected date from the calendar.'),
        ),
        migrations.AddField(
            model_name='usercycledata',
            name='previous_cycle_end',
            field=models.DateField(default=datetime.date.today, help_text='The selected date from the calendar.'),
        ),
        migrations.AddField(
            model_name='usercycledata',
            name='previous_cycle_start',
            field=models.DateField(default=datetime.date.today, help_text='The selected date from the calendar.'),
        ),
        migrations.AlterField(
            model_name='usercycledata',
            name='height',
            field=models.FloatField(help_text='Enter your height in cm'),
        ),
    ]
