# Generated by Django 5.1.2 on 2024-10-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_usercycledata_cycle_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercycledata',
            name='predicted_cycle_length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercycledata',
            name='predicted_next_cycle_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
