# Generated by Django 5.1.2 on 2024-10-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_event_alter_usercycledata_weight'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.AlterField(
            model_name='usercycledata',
            name='weight',
            field=models.PositiveIntegerField(help_text='Enter your weight in pounds.'),
        ),
    ]
